import { Quicksand } from 'next/font/google'
import StyledComponentsRegistry from './lib/registry';
import './globals.css'
import { CartProvider } from './hooks/useCart';
 
// If loading a variable font, you don't need to specify the font weight
const quicksand = Quicksand({  
  weight: '400',
  subsets: ['latin'], 
})
 
export const metadata = {
  title: 'The Coffee Place',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={quicksand.className}>
          <StyledComponentsRegistry>
            {children}
          </StyledComponentsRegistry>
        </body>
      </CartProvider>
    </html>
  )
}
